### ISSUE TITLE
VASCH5x2

### ISSUE THREAD

**Issue by sjoerdtimmer** [joeferner/kicad-library#1]
I've been wrong about such things in the past so please correct me if I'm mistaken.
I think there may be an issue with the VASCH5x2 header. pins are put on the following layers: front silk, front paste, front mask (and of course both copper layers). However, these headers are soldered from the bottom and since the "front/back mask" actually defines where the green solder resist will NOT be placed it should be on the bottom. I don't work with solder paste mask (amateur) but there may be a similar issue there depending on whether the convention is to show where solder paste should be or should not be...

**Comment by joeferner** [comment]
Most of the legacy folder could have mistakes. Those were created before I really knew what I was doing.
