### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ekaitz-zarraga** [joeferner/kicad-library#2]
Hi!

Sorry for opening an issue for this but I want to use one of your components and I don't know which License do you have and if it's ok to redistribute it.

Can you please add a license file for us to have as a reference?

Thank you very much.
This repo is very helpful.

**Comment by joeferner** [comment]
added the most permissive license I could think of.

**Comment by ekaitz-zarraga** [comment]
You have other more permissive options like public domain or WTFPL (Do What the Fuck You Want To Public License) license but MIT is enough.

Thanks a lot for taking the time.
